"""empty message

Revision ID: 161275d54fe0
Revises: fffae85bdf78
Create Date: 2023-08-15 14:47:24.156174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161275d54fe0'
down_revision = 'fffae85bdf78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iati_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iati_line_iati_identifier'), ['iati_identifier'], unique=False)
        batch_op.alter_column('iati_identifier',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iati_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iati_line_iati_identifier'))
        batch_op.alter_column('iati_identifier',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
