"""empty message

Revision ID: 1956c5d25718
Revises: 161275d54fe0
Create Date: 2024-04-30 09:43:02.707801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1956c5d25718'
down_revision = '161275d54fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iati_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iati_activity_reporting_organisation'), ['reporting_organisation'], unique=False)

    with op.batch_alter_table('iati_line', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_receiver_organisation_type', 'receiver_organisation_type', ['receiver_organisation_type'], ['code'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_provider_organisation_type', 'provider_organisation_type', ['provider_organisation_type'], ['code'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iati_line', schema=None) as batch_op:
        batch_op.drop_constraint('fk_receiver_organisation_type', type_='foreignkey')
        batch_op.drop_constraint('fk_provider_organisation_type', type_='foreignkey')

    with op.batch_alter_table('iati_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iati_activity_reporting_organisation'))

    # ### end Alembic commands ###
