"""empty message

Revision ID: 39b56c7ddfce
Revises: 
Create Date: 2023-02-01 16:14:53.265933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b56c7ddfce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iati_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_fr', sa.UnicodeText(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('title_pt', sa.UnicodeText(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('title_es', sa.UnicodeText(), nullable=False, server_default=''))

    with op.batch_alter_table('iati_line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_organisation_fr', sa.UnicodeText(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('provider_organisation_pt', sa.UnicodeText(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('provider_organisation_es', sa.UnicodeText(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('receiver_organisation_fr', sa.UnicodeText(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('receiver_organisation_pt', sa.UnicodeText(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('receiver_organisation_es', sa.UnicodeText(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iati_line', schema=None) as batch_op:
        batch_op.drop_column('receiver_organisation_es')
        batch_op.drop_column('receiver_organisation_pt')
        batch_op.drop_column('receiver_organisation_fr')
        batch_op.drop_column('provider_organisation_es')
        batch_op.drop_column('provider_organisation_pt')
        batch_op.drop_column('provider_organisation_fr')

    with op.batch_alter_table('iati_activity', schema=None) as batch_op:
        batch_op.drop_column('title_es')
        batch_op.drop_column('title_pt')
        batch_op.drop_column('title_fr')

    # ### end Alembic commands ###
