"""empty message

Revision ID: 450f2209139f
Revises: 09adb777bee6
Create Date: 2023-08-07 21:33:13.126368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450f2209139f'
down_revision = '09adb777bee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_organisation',
    sa.Column('id', sa.UnicodeText(), nullable=False),
    sa.Column('name_en', sa.UnicodeText(), nullable=False),
    sa.Column('name_fr', sa.UnicodeText(), nullable=False),
    sa.Column('name_pt', sa.UnicodeText(), nullable=False),
    sa.Column('name_es', sa.UnicodeText(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receiver_organisation',
    sa.Column('id', sa.UnicodeText(), nullable=False),
    sa.Column('name_en', sa.UnicodeText(), nullable=False),
    sa.Column('name_fr', sa.UnicodeText(), nullable=False),
    sa.Column('name_pt', sa.UnicodeText(), nullable=False),
    sa.Column('name_es', sa.UnicodeText(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('iati_line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_organisation_id', sa.UnicodeText(), nullable=True))
        batch_op.add_column(sa.Column('receiver_organisation_id', sa.UnicodeText(), nullable=True))
        batch_op.create_index(batch_op.f('ix_iati_line_provider_organisation_id'), ['provider_organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_iati_line_receiver_organisation_id'), ['receiver_organisation_id'], unique=False)
        batch_op.create_foreign_key('fk_receiver_organisation_id', 'receiver_organisation', ['receiver_organisation_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_provider_organisation_id', 'provider_organisation', ['provider_organisation_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iati_line', schema=None) as batch_op:
        batch_op.drop_constraint('fk_receiver_organisation_id', type_='foreignkey')
        batch_op.drop_constraint('fk_provider_organisation_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_iati_line_receiver_organisation_id'))
        batch_op.drop_index(batch_op.f('ix_iati_line_provider_organisation_id'))
        batch_op.drop_column('receiver_organisation_id')
        batch_op.drop_column('provider_organisation_id')

    op.drop_table('receiver_organisation')
    op.drop_table('provider_organisation')
    # ### end Alembic commands ###
