"""empty message

Revision ID: 56965fd5c1ff
Revises: 7d9e7b5c1d64
Create Date: 2023-02-05 15:47:46.385734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56965fd5c1ff'
down_revision = '7d9e7b5c1d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iati_activity', schema=None) as batch_op:
        batch_op.drop_index('ix_iati_activity_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iati_activity', schema=None) as batch_op:
        batch_op.create_index('ix_iati_activity_location', ['location'], unique=False)

    # ### end Alembic commands ###
