"""empty message

Revision ID: 75a6e15cb36b
Revises: ea0e91469811
Create Date: 2023-07-13 01:55:00.800831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a6e15cb36b'
down_revision = 'ea0e91469811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reporting_organisation_group',
    sa.Column('code', sa.UnicodeText(), nullable=False),
    sa.Column('name_en', sa.UnicodeText(), nullable=False),
    sa.Column('name_fr', sa.UnicodeText(), nullable=False),
    sa.Column('name_es', sa.UnicodeText(), nullable=False),
    sa.Column('name_pt', sa.UnicodeText(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('iati_activity', schema=None) as batch_op:
        # FIXME later, after migrating data, this should not be nullable
        batch_op.add_column(sa.Column('_hash', sa.UnicodeText(), nullable=True))
        batch_op.create_index(batch_op.f('ix_iati_activity__hash'), ['_hash'], unique=False)

    with op.batch_alter_table('iati_line', schema=None) as batch_op:
        # FIXME later, after migrating data, this should not be nullable
        batch_op.add_column(sa.Column('reporting_organisation_group', sa.UnicodeText(), nullable=True))
        batch_op.create_index(batch_op.f('ix_iati_line_reporting_organisation_group'), ['reporting_organisation_group'], unique=False)
        batch_op.create_foreign_key('iati_line_reporting_organisation_group_fkey', 'reporting_organisation_group', ['reporting_organisation_group'], ['code'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('iati_line', schema=None) as batch_op:
        batch_op.drop_constraint('iati_line_reporting_organisation_group_fkey', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_iati_line_reporting_organisation_group'))
        batch_op.drop_column('reporting_organisation_group')

    with op.batch_alter_table('iati_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iati_activity__hash'))
        batch_op.drop_column('_hash')

    op.drop_table('reporting_organisation_group')
    # ### end Alembic commands ###
