"""empty message

Revision ID: ea0e91469811
Revises: 56965fd5c1ff
Create Date: 2023-07-13 01:07:34.099490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea0e91469811'
down_revision = '56965fd5c1ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_organisation_type',
    sa.Column('code', sa.UnicodeText(), nullable=False),
    sa.Column('name_en', sa.UnicodeText(), nullable=False),
    sa.Column('name_fr', sa.UnicodeText(), nullable=False),
    sa.Column('name_es', sa.UnicodeText(), nullable=False),
    sa.Column('name_pt', sa.UnicodeText(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('receiver_organisation_type',
    sa.Column('code', sa.UnicodeText(), nullable=False),
    sa.Column('name_en', sa.UnicodeText(), nullable=False),
    sa.Column('name_fr', sa.UnicodeText(), nullable=False),
    sa.Column('name_es', sa.UnicodeText(), nullable=False),
    sa.Column('name_pt', sa.UnicodeText(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('iati_line', schema=None) as batch_op:
        batch_op.alter_column('provider_organisation_type',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('receiver_organisation_type',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_iati_line_provider_organisation_type'), ['provider_organisation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_iati_line_receiver_organisation_type'), ['receiver_organisation_type'], unique=False)
        #batch_op.create_foreign_key('iati_line_receiver_organisation_type_fkey', 'receiver_organisation_type', ['receiver_organisation_type'], ['code'], ondelete='CASCADE')
        #batch_op.create_foreign_key('iati_line_provider_organisation_type_fkey', 'provider_organisation_type', ['provider_organisation_type'], ['code'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iati_line', schema=None) as batch_op:
        #batch_op.drop_constraint('iati_line_receiver_organisation_type_fkey', type_='foreignkey')
        #batch_op.drop_constraint('iati_line_provider_organisation_type_fkey', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_iati_line_receiver_organisation_type'))
        batch_op.drop_index(batch_op.f('ix_iati_line_provider_organisation_type'))
        batch_op.alter_column('receiver_organisation_type',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('provider_organisation_type',
               existing_type=sa.TEXT(),
               nullable=True)

    op.drop_table('receiver_organisation_type')
    op.drop_table('provider_organisation_type')
    # ### end Alembic commands ###
