"""empty message

Revision ID: fffae85bdf78
Revises: 450f2209139f
Create Date: 2023-08-08 16:52:28.417441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffae85bdf78'
down_revision = '450f2209139f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('provider_organisation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_organisation_name_en'), [sa.text("left(name_en, 100)")], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_organisation_name_es'), [sa.text("left(name_es, 100)")], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_organisation_name_fr'), [sa.text("left(name_fr, 100)")], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_organisation_name_pt'), [sa.text("left(name_pt, 100)")], unique=False)

    with op.batch_alter_table('receiver_organisation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receiver_organisation_name_en'), [sa.text("left(name_en, 100)")], unique=False)
        batch_op.create_index(batch_op.f('ix_receiver_organisation_name_es'), [sa.text("left(name_es, 100)")], unique=False)
        batch_op.create_index(batch_op.f('ix_receiver_organisation_name_fr'), [sa.text("left(name_fr, 100)")], unique=False)
        batch_op.create_index(batch_op.f('ix_receiver_organisation_name_pt'), [sa.text("left(name_pt, 100)")], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_organisation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_organisation_name_en'))
        batch_op.drop_index(batch_op.f('ix_provider_organisation_name_es'))
        batch_op.drop_index(batch_op.f('ix_provider_organisation_name_fr'))
        batch_op.drop_index(batch_op.f('ix_provider_organisation_name_pt'))

    with op.batch_alter_table('receiver_organisation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receiver_organisation_name_en'))
        batch_op.drop_index(batch_op.f('ix_receiver_organisation_name_es'))
        batch_op.drop_index(batch_op.f('ix_receiver_organisation_name_fr'))
        batch_op.drop_index(batch_op.f('ix_receiver_organisation_name_pt'))

    # ### end Alembic commands ###
